### PR TITLE
Remove open source sha256 hash functions.

### LINKED ISSUE #943: Use common libs and avoid cut-n-paste of sources when there is a lib avaible
@sv641  raised it and I think this is important: 

There are 2 parts to this issue: (1) general approach (2) specific fix

1. We need to discuss (and hopefully agree) on the approach in cases we need some feature

- we need to always prefer standard library. It make is easier to maintain/allow to forget update updating and generally generates less headaches/responsibilities going forward
- any time we need an exception we need to discuss. An exception may be complexities in build/CI/install of the product
- if there are multiple choices, we prefer those picked up by folks at RedHat (just to simplify things) 

2. If we agree on the above, the we need to drop SHA code from krun and use libssl, as the first step - certainly NOT in the first release. so putting in in Next to triage

//CC @paulpopelka @gnode1 @sv641 

///

### PR DESCRIPTION
**Pull request by paulpopelka**
Switched crun/krun over to using the sha256 hash functions in openssl.
krun now links with libcrypto and libssl and the open sha256 code is removed.

Tested using the crun test scripts.

Fixes https://github.com/kontainapp/km/issues/943

### CODE REVIEW

**Review by gnode1 — APPROVED** [review]

**Comment by msterin** [comment]
do we have both of these libs in buildenv-image ? (or, did you test with `make withdocker' build ?

**Comment by paulpopelka** [comment]
> do we have both of these libs in buildenv-image ? (or, did you test with `make withdocker' build ?

I did a "make pull-buildenv-image" and then tried "make withdocker" and it succeeded.  
I assumed that libcrypto and libssl would just be there.  These things are basically a fundamental layer in our crooked world.

I could add openssl-libs to the "RUN dnf install -y ....." in tests/buildenv-fedora.dockerfile but we already install "openssl-devel openssl-static" there.  That seems to imply openssl is already there.

Or, maybe it is more subtle than I assume.

**Comment by msterin** [comment]
> > do we have both of these libs in buildenv-image ? (or, did you test with `make withdocker' build ?
> 
> I did a "make pull-buildenv-image" and then tried "make withdocker" and it succeeded.
> I assumed that libcrypto and libssl would just be there. These things are basically a fundamental layer in our crooked world.
> 
> I could add openssl-libs to the "RUN dnf install -y ....." in tests/buildenv-fedora.dockerfile but we already install "openssl-devel openssl-static" there. That seems to imply openssl is already there.
> 
> Or, maybe it is more subtle than I assume.

if you just search for this lib in the docker image that would be enough, something like this
`docker run -u 0 --rm kontain/buildenv-km-fedora find / -name lib\*ssl\*`
No subtlety, it's either there or not :-)

**Review by sv641 — COMMENTED** [review]
Changes to crun need to confirm to crun coding style.
They provide a .clang-format file.

**Review by sv641 — COMMENTED** [review]
deleted. Does not apply.

**Review by sv641 — COMMENTED** [review]
There seems to be a built in hash function in signals.c, it is not strong crypto hash we may want to take a look at it before adding library.

**Comment by paulpopelka** [comment]
> There seems to be a built in hash function in signals.c, it is not strong crypto hash we may want to take a look at it before adding library.

Are you referring to this source file: ./crun/src/libcrun/signals.c
gperf generated that file.  The hash function it builds is tailored to a specific set of strings provided to the gperf tool.
That hash function doesn't seem suited to the executable files we are computing the hash of.
The code seems to be generated for the abbreviations of linux signal names.

**Comment by paulpopelka** [comment]
> Changes to crun need to confirm to crun coding style.
> They provide a .clang-format file.

I'll do that.  Their style is quite different from kontain's.

**Review by paulpopelka — COMMENTED** [review]
Yes, libssl and libcrypto are present in the buildenv image
```
[paulp@work km]$ docker run -u 0 --rm kontain/buildenv-km-fedora find / -name lib\*ssl\*
/opt/kontain/alpine-lib/lib/libssl.so.1.1
/opt/kontain/alpine-lib/usr/lib/libssl.so.1.1
/usr/lib64/libssl.so.1.1
/usr/lib64/pkgconfig/libssl.pc
/usr/lib64/libssl.a
/usr/lib64/libevent_openssl-2.1.so.6.0.2
/usr/lib64/libssl.so
/usr/lib64/libevent_openssl-2.1.so.6
/usr/lib64/libssl.so.1.1.1g
[paulp@work km]$ docker run -u 0 --rm kontain/buildenv-km-fedora find / -name lib\*crypto\*
/opt/kontain/alpine-lib/lib/libcrypto.so.1.1
/opt/kontain/alpine-lib/usr/lib/libcrypto.so.1.1
/usr/lib64/libk5crypto.so.3.1
/usr/lib64/libk5crypto.so.3
/usr/lib64/libcrypto.so.1.1
/usr/lib64/libcrypto.so
/usr/lib64/pkgconfig/libcrypto.pc
/usr/lib64/libcrypto.a
/usr/lib64/libcrypto.so.1.1.1g
[paulp@work km]$
```

**Comment by msterin** [comment]
> > Changes to crun need to confirm to crun coding style.
> > They provide a .clang-format file.
> 
> I'll do that. Their style is quite different from kontain's.

Please do in a dedicated commit

Also - visual studio is supposed to do it automatically as long as a correct .clang-format is in the folder :-)

**Pull request merged**
